name: Spark testing main

on: push 

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - uses: actions/setup-java@v1
      with:
        java-version: '11'

    - uses: vemonet/setup-spark@v1
      with:
        spark-version: '3.2.1'
        hadoop-version: '3.2'
    - name: Run one script
      run: echo hello world!
      
