name: Spark testing main

on:
  push:
    branches:
      - 'main'
      - 'dev'
    paths:
      - 'pipeline/Spark/src/use_cases/spark_price_at_an_instant.py'
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - 'main'
      - 'dev'
    paths:
      - 'pipeline/Spark/src/use_cases/spark_price_at_an_instant.py' 

jobs:
  testing:
    uses: ./.github/workflows/testing.yml
    with:
        usecase_name: price_at_an_instant
        

      
      
