name: Spark testing main

on: push 

jobs:
  testing_spaai:
    uses: parthsaini08/testing_spark/.github/workflows/testing.yml@main
    with:
        usecase_name: price_at_an_instant
  testing_sprr:
    name: Testing product relative reach
    uses: parthsaini08/testing_spark/.github/workflows/testing.yml@main
    with:
        usecase_name: product_relative_reach
      
      
