name: Spark testing main

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: testing spark main
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: actions/testing_spark@v1
        with:
          usecase_name: 'price_at_an_instant'
      
      
