name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - uses: actions/setup-java@v1
      with:
        java-version: '11'

    - uses: vemonet/setup-spark@v1
      with:
        spark-version: '3.2.1'
        hadoop-version: '3.2'
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: testing
      run: |
        cd tests
        python spark_test -t product_relative_reach
