name: Spark testing main

on:
  push:
    branches:
      - 'main'
    paths:
      - 'pipeline/Spark/src/use_cases/spark_price_at_an_instant.py'
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - 'main'
      - 'dev'
    paths:
      - 'pipeline/Spark/src/use_cases/spark_price_at_an_instant.py' 

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: owner name
      run: |
        echo "${{github.repository.owner}}"
        

      
      
